language: php

php:
  - 7.0

cache:
  directories:
    - vendor
    - ~/.composer/cache

before_install:
  - composer install --prefer-source --no-interaction

script:
  - vendor/bin/phpunit -c phpunit.xml --debug

notifications:
  email:
    - lazos@lazos.me
