language: php

php:
  - 5.6
  - 7.0

git:
  depth: 1

cache:
  directories:
    - vendor
    - ~/.composer/cache

before_install:
  - composer install --prefer-source --no-interaction

#before_script:
#  - phpenv config-add tests/php.ini

script:
  - vendor/bin/phpunit -c phpunit.xml --debug

notifications:
  email:
    - lazos@lazos.me
